name: "Deploy to NuGet"

on: ["push"]

env:
  PROJECT_PATH: 'Repository\Repository.Implementation\Repository.Implementation.csproj'
  PROJECT_INTERFACE_PATH: 'Repository\Repository.Interfaces\Repository.Interfaces.csproj'
  PACKAGE_OUTPUT_DIRECTORY_IMPLEMENTATION: ${{ github.workspace }}\output\implementation
  PACKAGE_OUTPUT_DIRECTORY_INTERFACES: ${{ github.workspace }}\output\interfaces
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'


jobs:
  build_and_push:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: edumserrano/nuget-push@v1.2.2
    - name: Build and Pack projects
      run: |
        for file in $(find . -name '*.csproj' ! -name '*test.csproj'); do 
          echo "Building project: $file"
          dotnet build $file --configuration Release
          dotnet pack $file --no-build --configuration Release
        done
    - name: Push NuGet packages
      uses: nuget/push@v1
      with:
        nuget-api-key: oy2adyglhhnlwk4yru5ae2ulh2xct2au7ljtikcm5saooi
        nuget-source: https://api.nuget.org/v3/index.json
        nuget-packages: '**/*.nupkg'