name: "Deploy to NuGet"

on: ["push"]

env:
  PROJECT_PATH: 'Repository\Repository.Implementation\Repository.Implementation.csproj'
  PROJECT_INTERFACE_PATH: 'Repository\Repository.Interfaces\Repository.Interfaces.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deployment'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: 'Restore packages Implementation'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Restore packages Interface'
      run: dotnet restore ${{ env.PROJECT_INTERFACE_PATH}}

    - name: 'Build project Implementation'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Build project Interface'
      run: dotnet build ${{ env.PROJECT_INTERFACE_PATH }} --no-restore --configuration Release

    - name: 'Pack project Implementation'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion='0.0.1' --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Pack project Implementation'
      run: dotnet pack ${{ env.PROJECT_INTERFACE_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion='0.0.1' --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package Implementation'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}