name: Publish NuGet packages

permissions: 
  contents: write
  packages: write
  

# Controls when the action will run. 
on:
  push:
    branches: 
    - main
#    - develop
    - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  publish-nuget:
    name: Publish NuGet package
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore **/*.csproj

      - name: Build
        run: dotnet build **/*.csproj

      - id: is-public-release
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ steps.nbgv.outputs.PublicRelease }}

      # Publish
      - name: Build, Pack & Publish
        id: publish_nuget
        uses: Rebel028/publish-nuget@v2.7.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Repository\Repository.Implementation\Repository.Implementation.csproj
          
          # NuGet package id, used for version detection & defaults to project name
          # PACKAGE_NAME: Core
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: 0.0.6

          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: ${{ steps.is-public-release.outputs.lowercase }}

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: v${{ steps.nbgv.outputs.MajorMinorVersion }}

          # API key to authenticate with NuGet server
          NUGET_KEY: oy2adyglhhnlwk4yru5ae2ulh2xct2au7ljtikcm5saooi

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org/v3/index.json

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true